services:
  webserver:
    build:
      context: .
      dockerfile: dockerfile
    container_name: googolplex_website
    ports:
      - "3050:4080"
    volumes:
      - ./:/googolplex_website
    working_dir: /googolplex_website
    command: python -m http.server 4080
    restart: unless-stopped
